sudo: required
dist: trusty

services: docker

language: java

script:
 - docker-compose up --build -d
 - docker ps -a
 - docker run hello-world
 - ant;
 - ant test;

after_script:
 - docker-compose down
