sudo: required
dist: trusty

install:
  # Update docker-engine using Ubuntu 'trusty' apt repo
  - >
	sudo apt-get update
  - >
	sudo apt-get install docker-ce
language: java

script:
 - ant;
 - ant test;
